# Table sections and columns
sections:
  - id: info
    title: Character Info
    icon: id-card
    columns:
      - id: name
        title: Name
        icon: signature
        jsonPath: build.name
        highestValue: false
      - id: class
        title: Class
        icon: hat-wizard
        jsonPath: build.class
        highestValue: false
        displayType: pill
      - id: archetypes
        title: Archetypes
        icon: mortar-pestle
        jsonPath: extracted.archetypes
        highestValue: false
        displayType: pill-list
      - id: level
        title: Level
        icon: award
        jsonPath: build.level
        highestValue: true
      - id: keyAttribute
        title: Key Attr
        icon: key
        jsonPath: build.keyability
        highestValue: false
        displayType: pill

  - id: healing
    title: Healing & Sustain
    icon: heart-pulse
    columns:
      - id: healingAbilities
        title: Abilities
        icon: kit-medical
        jsonPath: extracted.healingAbilities
        highestValue: false
        displayType: pill-list

  - id: ability
    title: Ability Scores
    icon: dumbbell
    columns:
      - id: str
        title: STR
        jsonPath: build.abilities.str
        highestValue: true
      - id: dex
        title: DEX
        jsonPath: build.abilities.dex
        highestValue: true
      - id: con
        title: CON
        jsonPath: build.abilities.con
        highestValue: true
      - id: int
        title: INT
        jsonPath: build.abilities.int
        highestValue: true
      - id: wis
        title: WIS
        jsonPath: build.abilities.wis
        highestValue: true
      - id: cha
        title: CHA
        jsonPath: build.abilities.cha
        highestValue: true

  - id: perception
    title: Perception
    icon: eye
    columns:
      - id: perception
        title: Perc
        icon: eye
        fullTitle: Perception
        jsonPath: extracted.skills.perception
        proficiencyPath: extracted.skillProficiencies.perception
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true

  - id: defense
    title: Defenses
    icon: shield-halved
    columns:
      - id: ac
        title: AC
        jsonPath: build.acTotal.acTotal
        highestValue: true
      - id: fort
        title: Fort
        jsonPath: extracted.defenses.fort
        highestValue: true
      - id: ref
        title: Ref
        jsonPath: extracted.defenses.ref
        highestValue: true
      - id: will
        title: Will
        jsonPath: extracted.defenses.will
        highestValue: true

  - id: skills
    title: Skills
    icon: graduation-cap
    columns:
      - id: acrobatics
        title: Acro
        icon: person-falling
        fullTitle: Acrobatics
        jsonPath: extracted.skills.acrobatics
        proficiencyPath: extracted.skillProficiencies.acrobatics
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: arcana
        title: Arca
        icon: wand-sparkles
        fullTitle: Arcana
        jsonPath: extracted.skills.arcana
        proficiencyPath: extracted.skillProficiencies.arcana
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: athletics
        title: Athl
        icon: person-running
        fullTitle: Athletics
        jsonPath: extracted.skills.athletics
        proficiencyPath: extracted.skillProficiencies.athletics
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: crafting
        title: Craf
        icon: hammer
        fullTitle: Crafting
        jsonPath: extracted.skills.crafting
        proficiencyPath: extracted.skillProficiencies.crafting
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: deception
        title: Dece
        icon: mask
        fullTitle: Deception
        jsonPath: extracted.skills.deception
        proficiencyPath: extracted.skillProficiencies.deception
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: diplomacy
        title: Dipl
        icon: handshake
        fullTitle: Diplomacy
        jsonPath: extracted.skills.diplomacy
        proficiencyPath: extracted.skillProficiencies.diplomacy
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: intimidation
        title: Inti
        icon: face-angry
        fullTitle: Intimidation
        jsonPath: extracted.skills.intimidation
        proficiencyPath: extracted.skillProficiencies.intimidation
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: medicine
        title: Medi
        icon: stethoscope
        fullTitle: Medicine
        jsonPath: extracted.skills.medicine
        proficiencyPath: extracted.skillProficiencies.medicine
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: nature
        title: Natu
        icon: leaf
        fullTitle: Nature
        jsonPath: extracted.skills.nature
        proficiencyPath: extracted.skillProficiencies.nature
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: occultism
        title: Occu
        icon: eye
        fullTitle: Occultism
        jsonPath: extracted.skills.occultism
        proficiencyPath: extracted.skillProficiencies.occultism
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: performance
        title: Perf
        icon: masks-theater
        fullTitle: Performance
        jsonPath: extracted.skills.performance
        proficiencyPath: extracted.skillProficiencies.performance
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: religion
        title: Reli
        icon: pray
        fullTitle: Religion
        jsonPath: extracted.skills.religion
        proficiencyPath: extracted.skillProficiencies.religion
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: society
        title: Soci
        icon: landmark
        fullTitle: Society
        jsonPath: extracted.skills.society
        proficiencyPath: extracted.skillProficiencies.society
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: stealth
        title: Stea
        icon: user-ninja
        fullTitle: Stealth
        jsonPath: extracted.skills.stealth
        proficiencyPath: extracted.skillProficiencies.stealth
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: survival
        title: Surv
        icon: campground
        fullTitle: Survival
        jsonPath: extracted.skills.survival
        proficiencyPath: extracted.skillProficiencies.survival
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
      - id: thievery
        title: Thie
        icon: lock-open
        fullTitle: Thievery
        jsonPath: extracted.skills.thievery
        proficiencyPath: extracted.skillProficiencies.thievery
        showProficiency: true
        displayType: proficiency-badge
        highestValue: true
